seconds=input("Enter number of seconds:")
seconds= int(seconds)
minutes=int(seconds/60)
hours=int(minutes/60)
r=seconds%60
str(seconds)
str(minutes)
str(hours)
str(r)
print (str(seconds)+ " is " + str(hours)+ " hours, " + str(minutes) + " minutes and "+ str(r)+ " seconds ")